@startmindmap QuizU NavMap

* Welcome

** Create Account
*** Dashboard
**** Course Quiz List
***** Quiz Questions
****** Quiz Results 

** Log In
*** Dashboard
**** Course Quiz List
***** Quiz Questions
****** Quiz Results 

@endmindmap
